version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24

  pre_build:
    commands:
      - cd web && yarn install --frozen-lockfile

  build:
    commands:
      - cd web && yarn build
